StafflinePeoplePlus/peopleplus-components

.github/workflows/publish.yml
Adds a github action set to run on pushes to main that will:
- Run Tests to ensure we don't publish something with failing tests
- Runs the [npm-publish](https://github.com/marketplace/actions/npm-publish) to publish to npm if the version in the `package.json` is not already published
- Runs the [commit-comment](https://github.com/marketplace/actions/commit-comment) to add a comment about the version being published to the commit that caused it to happen
PR to main as the action only happens on main, but I can change it to uat as usual if you'd prefer
The action is untested as I'm not sure of a great way to test without just trying it on main
We will need a secret added as `NPM_TOKEN`
=> add github action to publish to npm when the package.json version changes

package-lock.json, package.json, src/lib/Carousel.svelte, src/lib/index.ts, src/routes/+layout.svelte, src/routes/Carousel/+page.svelte, src/routes/Carousel/ExampleCarousel.svelte
Adds a horizontal carousel component using `swiper` under the hood. Currently this focuses on catering for the one variant that we are using, but swiper has a lot of options and there is room for supporting those different variants as and when we need them.
Not too sure on a great way of testing this so I've left it for now
=> Add carousel component

src/app.html, src/routes/+layout.svelte, src/routes/+page.svelte, src/routes/guidelines/+page.svelte
Adds an implementation guidelines page. Currently just has two guidelines on top of the goals set out on the homepage.
We can add more as we discover/think of them.
=> add implementation guidelines page

package.json, src/lib/tailwind.ts, src/lib/video/HorizontalRange.svelte, src/lib/video/VerticalRange.svelte, src/lib/video/VideoPlayer.svelte, tailwind.config.js
Adds a tailwind plugin for styling the range-thumb that makes it easier to cater for both webkit and firefox - it seems likely we would want to add other utilities in the future and other frameworks also have tailwind plugins so it seems reasonable.
=> fix play/pause and range styling in firefox

src/lib/Carousel.svelte
I'm guessing theres some subtle tree shaking bug when using it inline which means that import gets kept in on server builds of the component. Moving the use of throttle to within the script block seems to fix it.
Fixes #290
=> move resize listener up to avoid false warning about throttle

.github/workflows/publish.yml
recent release failed to push the changelog as it doesn't know what tag to associate the release with
=> explicitly give tag name to create gh release action

package.json
This was incorrectly tagged as a svelte specific export causing it to be unimportable in node.
=> fix export of tailwind plugin

src/lib/banner/Banner.svelte, src/lib/banner/Banner.test.ts, src/lib/banner/TestBanner.svelte, src/routes/(docs)/Banner/ExampleBanner.svelte
I think it makes more sense for the actual hiding of the banner to be handled externally to the banner component itself.
This PR changes the dismiss button to fire the `dismiss` event instead of hide the banner itself. This way the consumer of the component can choose how the banner gets hidden and can react to the dismiss by, for example, adding a cookie, or showing a different banner etc.
=> fire dismiss event on banner instead of hiding itself

package-lock.json, package.json
This was erroneously in the dev dependencies meaning that when installing in a new project that isn't already using lucide-svelte the module would not be found.
=> move lucide-svelte to dependencies

src/lib/forms/InputLabel.svelte
the use property was erroneously marked as required on the InputLabel component, this fixes that.
=> make use property optional on input label

package-lock.json, package.json, src/lib/Button.svelte, src/lib/Dropdown.svelte, src/lib/cookies/CookieConsentBanner.svelte, src/lib/toaster/Toast.svelte, src/lib/video/VideoPlayer.svelte
Don't see much value in trying to support both v3 and v4 when afaik we are the only consumer at the moment.
=> update to only support svelte v4, closes #354

playwright_tests/Toaster.spec.ts
updates toaster test to use the modified version of goto that we use elsewhere that will wait for svelte to have hydrated the page before finishing.
=> use custom test fixture in toaster tests to fix flakiness

src/lib/forms/Switch.svelte, src/routes/(docs)/Switch/ExampleSwitch.svelte
`bind:group` is a little special in svelte so we can't simply pass through the binding like normal so we emulate what bind:group does instead.
=> add support for bind:group on Switch component

src/lib/forms/Switch.svelte, src/routes/(docs)/Switch/ExampleSwitch.svelte
previous bind:group emulation was not quite complete as it doesn't handle initial values of the group, and external changes to the group. This PR fixes that
=> handle external changes to bind:group in Switch

.github/workflows/ci-main.yml
Tests with coverage seem to trip github actions up quite often, so this PR separates out the test coverage and publishing jobs into two separate jobs. The publish job still runs the tests to make sure they pass before publishing.
More work to be done to figure out why the coverage tests end up being so flakey on the actions runner (even with a beefy one), when locally they run fine both on mac and in a linux vm (admittedly arm64 for both)
=> separate out coverage and publish into separate jobs

src/lib/Avatar.svelte, src/lib/index.ts, src/lib/sidebar/Sidebar.svelte, src/lib/sidebar/SidebarItem.svelte, src/lib/sidebar/index.ts, src/routes/(docs)/components/+layout.svelte, src/routes/(docs)/components/Sidebar/+page.svelte, src/routes/(docs)/components/UsageSection.svelte, src/routes/(docs)/components/index.ts, src/routes/usage/sidebar/+page.svelte
closes #1014 
I chose not to add the 'mobile' version as this is effectively a drawer with the sidebar in it. The drawer needs converting to melt-ui and then perhaps an example can be added.
=> add sidebar component

.changeset/popular-rats-press.md, src/lib/sidebar/SidebarItem.svelte
The SideBarItem active colour is now set to the primary colour and keeps the grey background for the hover state.
=> update active state on side bar item

.changeset/early-olives-destroy.md, CHANGELOG.md, package.json, vite.config.ts
I'd like to get a `0.1.0` release out to make it easier to share the components across packages. Right now as we are on 0.0.x releases, every release counts as a breaking release and as such it makes every version incompatible with another from NPM's perspective. This makes using packages that depend on the components (such as `@peopleplus/cohort-management`) annoying to use and maintain as every update to the components requires an update to the dependent package.
This PR contains a changeset that will bump the minor version and I'm also taking this opportunity to rename the package from `pp-svelte-components` to `@peopleplus/components`.
=> rename package to be under npm org

.changeset/dull-ducks-bow.md, src/lib/collapsible/Collapsible.svelte, src/lib/toaster/Toast.svelte, src/lib/video/FullscreenButton.svelte, src/lib/video/VideoPlayer.svelte, src/lib/video/VolumeControl.svelte, src/routes/(docs)/components/CodeSnippet.svelte, src/routes/usage/dropdownMenu/+page.svelte, src/routes/usage/navbar/+page.svelte, src/routes/usage/sidebar/+page.svelte, src/routes/usage/sortable/grid/+page.svelte, src/routes/usage/sortable/horizontal/+page.svelte, src/routes/usage/sortable/vertical/+page.svelte, src/routes/usage/tooltip/+page.svelte, tsconfig.json
saves transpiling _all_ icons on build, saves about 5 seconds locally on a build of this project, saves 2-3x that in other projects.
=> import lucide icons directly for faster build times

.changeset/selfish-readers-tickle.md, src/app.html, src/lib/floating.ts, src/lib/index.ts, src/lib/popover/action.ts, src/lib/tooltip/Tooltip.svelte, src/routes/usage/+layout.svelte, src/routes/usage/tooltip/+page.svelte, src/routes/usage/tooltip/custom/+page.svelte
- adds dark mode support to tooltips
- fixes light mode when a text color wasn't already set
- fixed up the usage template to render things a little nicer
- improved the behaviour of the tooltip by:
- including a small delay by default
- closing the tooltip on pointer down by default
- disabling hoverable content by default
- all of the above is configurable now
- share floating types between tooltip and popover
=> support dark mode tooltips, improve default behaviour

.changeset/popular-dragons-beg.md, src/lib/popover/action.ts
allows controlling the popover from an externally provided source, for example to prevent more then one popover in some defined group from being open at any one time.
=> allow passing 'open' store to popover

.changeset/olive-dots-attack.md, src/lib/calendar/Calendar.svelte
=> fix alignment of calendar text in firefox

.changeset/nasty-frogs-melt.md, src/lib/dropdownMenu/DropdownMenu.svelte
When the component is generated, a class with the same name as the file is created. This happened to match the name of the imported type `DropdownMenu` causing the class to be used instead of the imported type for the `menu` property. This caused type mismatches when trying to use this property.
=> fix DropdownMenu `menu` type in generated types

.changeset/cuddly-goats-brake.md, .changeset/old-schools-yawn.md, .gitignore, src/lib/popover/action.ts
also exposes the close action/props from the melt-ui popover
=> allow disabling click outside to close on popovers
