package-lock.json
package.json
playwright_tests/test.spec.ts
src/routes/+page.svelte
src/routes/ExamplePage.svelte
tailwind.config.js

Sets out the goals of the project on the homepage - let me know if I've missed anything or what i've laid out don't align with the consensus.
Also added a quick acknowledgments section at the bottom.
Preview: https://feat-goals.peopleplus-components.pages.dev/
Closes #177 
Closes #84

lay out goals of the project on the homepage

---

src/app.css
src/app.d.ts
src/app.html
src/hooks.server.ts
src/lib/CodeSnippet.svelte
src/lib/DarkMode.svelte
src/lib/accordion/Accordion.svelte
src/lib/index.ts
src/routes/+layout.svelte
src/routes/DarkMode/+page.svelte
src/routes/DarkMode/ExampleDarkMode.svelte

Added dark mode/light mode button

Added Dark Mode as a component

---

package-lock.json
package.json
playwright.config.ts
playwright_tests/Carousel.spec.ts
playwright_tests/NavBar.spec.ts
src/lib/Carousel.svelte
src/routes/(docs)/Carousel/ExampleCarousel.svelte
src/routes/test/carousel/+page.svelte

Removes swiper in favour of a custom carousel implementation.
Still to do:

pure svelte implementation of the carousel

---

CODE_OF_CONDUCT.md
package-lock.json
package.json
playwright.config.ts
playwright_tests/Carousel.spec.ts
playwright_tests/NavBar.spec.ts
src/lib/Carousel.svelte
src/routes/test/carousel/+page.svelte

* pure svelte implementation of the carousel
* simplify styling on the example carousel
* add announcment of visible items and hide off screen items
* show scrollbar when the user has no javascript
* disable next and previous buttons when at extents
* add tests and fix bugs made apparent by the tests!
---------

pure svelte implementation of the carousel (#223)

---

.github/workflows/publish.yml

fix value of node cache on publish workflow

---

src/lib/jumbotron/Jumbotron.svelte
src/routes/(docs)/Jumbotron/ExampleJumbotron.svelte
src/routes/test/jumbotron/+page.svelte

* Fixed #317 - jumbotron width
* Fixed #317 - height and width, and add a test page.
* Fix format

Fixed #317 - jumbotron width (#318)

---

src/lib/navbar/NavItem.svelte

Allow additional props in the NavItem

---

src/lib/forms/InputLabel.svelte
src/lib/forms/Switch.svelte
src/lib/forms/Switch.test.ts
src/lib/forms/index.ts
src/routes/(docs)/+layout.svelte
src/routes/(docs)/Switch/+page.svelte
src/routes/(docs)/Switch/ExampleSwitch.svelte
svelte.config.js

add Switch component (#370)

---

src/lib/index.ts
src/lib/table/Table.svelte
src/lib/table/TableCell.svelte
src/lib/table/TableRow.svelte
src/lib/table/context.ts
src/lib/table/index.ts
src/lib/table/position.ts
src/routes/(docs)/+layout.svelte
src/routes/(docs)/Table/+page.svelte
src/routes/(docs)/Table/ExampleTable.svelte

* add Table component
* support dark mode

add Table component (#388)

---

src/lib/CodeSnippet.svelte
src/lib/navbar/NavBar.svelte
src/lib/video/FullscreenButton.svelte
src/lib/video/ScrubBar.svelte
src/lib/video/VideoPlayer.svelte
src/lib/video/VolumeControl.svelte
src/routes/(docs)/+layout.svelte
src/routes/(docs)/VideoPlayer/ExampleVideoPlayer.svelte

- Fixes using the controls with touch
- Improves mobile responsiveness of controls
- Updates docs page layout to make the mobile view usable
fixes #364

improve player controls on mobile devices

---

src/lib/media.ts
src/lib/navbar/NavBar.svelte

we already had md, this adds them all

add all screen media queries

---

playwright_tests/Carousel.spec.ts
src/lib/Carousel.svelte
src/routes/(docs)/Carousel/ExampleCarousel.svelte

a11ywatch flagged this as an issue

move carousel buttons outside of ul element

---

src/lib/banner/Banner.svelte
src/lib/banner/Banner.test.ts
src/lib/banner/TestBanner.svelte
src/routes/(docs)/Banner/ExampleBanner.svelte

* fire dismiss event on banner instead of hiding itself
* dismissable should not be required

fire dismiss event on banner instead of hiding itself (#556)

---

playwright.config.ts

porting these settings over from another project, should help with flaky tests

change some playwright options for CI

---

src/lib/accordion/Accordion.svelte
src/routes/(docs)/Accordion/ExampleAccordion.svelte

Not sure if this is the correct practice to allow multiple class overwrite, but let me know.

Add tailwind merge in accordion

---

package.json
src/app.d.ts
src/lib/actions.ts
src/lib/banner/Banner.svelte
src/lib/drawer/Drawer.svelte
src/lib/jumbotron/TestJumbotron.svelte
src/lib/toaster/Toast.svelte
src/lib/toaster/types.ts

add svelte check to lint and resolve all errors

---

package-lock.json
package.json

downgrade vitest to 0.33 due to vitest bug

---

src/lib/Carousel.svelte

allow touch-pan-y only on carousel

---

src/lib/Avatar.svelte
src/lib/index.ts
src/lib/sidebar/Sidebar.svelte
src/lib/sidebar/SidebarItem.svelte
src/lib/sidebar/index.ts
src/routes/(docs)/components/+layout.svelte
src/routes/(docs)/components/Sidebar/+page.svelte
src/routes/(docs)/components/UsageSection.svelte
src/routes/(docs)/components/index.ts
src/routes/usage/sidebar/+page.svelte

* add sidebar component
* use sidebar for docs
* dark mode sidebar

add sidebar component (#1071)

---

.changeset/lucky-steaks-collect.md
src/global.d.ts
src/lib/drawer/Drawer.svelte
src/lib/drawer/clickOutside.ts
src/lib/drawer/test/DrawerTest.svelte
src/routes/usage/drawer/+page.svelte

The drawer component is now supporting new features such as:
1. Custom styling on the negative space with `overlayClass`
2. The built-in 'Close Drawer' button is removed and can be added to the slot 
3. Dismissing the drawer by clicking outside the area, and can be disabled by using `disableClickOutside` in the component prop.

Update drawer component

---

.gitignore
.prettierignore

skip formatting test results

---

.changeset/sharp-ghosts-try.md
src/lib/collapsible/Collapsible.svelte
src/lib/collapsible/Collapsible.test.ts
src/lib/collapsible/TestCollapsible.svelte
src/lib/index.ts
src/routes/(docs)/components/Collapsible/+page.svelte
src/routes/(docs)/components/index.ts
src/routes/usage/collapsible/+page.svelte
src/routes/usage/collapsible/custom/+page.svelte

* add collapsible test
* fix test
* fix test
* resolve comments
* add changeset

Add a Collapsible Component (#1129)

---

.changeset/two-maps-vanish.md
src/lib/Stepper.svelte

Apply Consistency: Fix stepper border radius. Fixed #1060

Fix stepper border radius

---

.changeset/sour-windows-join.md
.changeset/twelve-falcons-remember.md
src/lib/index.ts
src/lib/tooltip/TestTooltip.svelte
src/lib/tooltip/Tooltip.svelte
src/lib/tooltip/Tooltip.test.ts
src/routes/(docs)/components/Tooltip/+page.svelte
src/routes/(docs)/components/index.ts
src/routes/usage/tooltip/+page.svelte
src/routes/usage/tooltip/custom/+page.svelte

Create tooltip component: https://feat-create-tooltip-componen.peopleplus-components.pages.dev/components/Tooltip
Closes #584

Create tooltip component

---

src/lib/cookies/CookieConsentBanner.test.ts

fix cookie banner test

---

src/lib/video/YouTubePlayer.svelte
tsconfig.json

Typeerror egetcurrenttime is not a function

---

.github/workflows/ci-main.yml
package.json

Fix istanbul deprecated warning

---

.changeset/nasty-cars-heal.md
src/lib/footer/Footer.svelte

Fixing the overlapping email bug on footer 
Closes #1244

Bug fix footer padding

---

.changeset/fuzzy-spies-notice.md
src/lib/footer/Footer.svelte

Remove the width restriction from footer. Fixed #1267

Remove the width restriction from footer

---

.changeset/three-mangos-heal.md
src/lib/footer/Footer.svelte

Add a `topClass` prop in the footer to allow changes on breakpoint

Allow changes on breakpoint in footer

---

.changeset/curvy-cycles-relax.md
.changeset/fast-pugs-travel.md
.changeset/plenty-donkeys-mate.md
.changeset/two-houses-poke.md
src/lib/calendar/Calendar.svelte

see changesets for a summary of each change

various calendar fixes

---

.changeset/moody-kings-tan.md
.changeset/pretty-onions-explode.md
.changeset/rich-shoes-speak.md
.changeset/strange-parents-brake.md
.changeset/weak-sloths-glow.md
src/lib/Button.svelte
src/lib/calendar/Calendar.svelte
src/routes/(docs)/components/Button/+page.svelte
src/routes/usage/button/+page.svelte
src/routes/usage/button/icon/+page.svelte
src/routes/usage/button/shapes/+page.svelte
src/routes/usage/button/sizes/+page.svelte

See the changesets for list of all changes

add more button variants and tweak default styling

---

.changeset/empty-needles-exist.md
src/lib/drawer/Drawer.svelte

add `onClose` prop to Drawer

---

.changeset/dirty-sloths-sniff.md
.changeset/large-mails-provide.md
src/lib/drawer/Drawer.svelte
src/lib/toaster/Toaster.svelte

order toaster and tooltips above drawers

---

.changeset/polite-points-approve.md
src/lib/toaster/Toaster.svelte

throw helpful error when trying to use showToast on the server
